### ISSUE TITLE
Build issue on Windows with MinGW

### ISSUE THREAD

**Issue by bolt2strike** [marcobambini/gravity#38]
I'm having a build error with MinGW on Windows 10 trying to build the github after cloning

The full error log is available in a pastebin [here](http://pastebin.com/s2gpnkGk)

The log seems to indicate inline functions being declared never being properly defined

**Comment by hallzy** [comment]
The inline function things look like warnings, and I get those on Ubuntu as well, so I probably wouldn't worry about those.

The rest of it is probably where the issue lies

**Comment by badcc** [comment]
Yeah, issue is the undefined references.

**Comment by brandon-ray** [comment]
It looks like gravity_utils.c and gravity_macros.c are not being compiled or even attempted to be compiled for some reason.

**Comment by hallzy** [comment]
@bolt2strike would you mind pulling the latest changes and trying again? There was recently a PR that was merged ( #39 ) that should resolve the warnings. I have doubts that it will solve the problem, but at the very least it will cleanup the output. Also, as far as I know we have yet to test that PR on a windows machine, and it would be nice to know that it works for windows.

**Comment by bolt2strike** [comment]
@hallzy I can confirm that pull request #39 removed the warnings however the rest of the errors are indeed still present

[New pastebin](http://pastebin.com/UsUNnpms)

**Comment by bolt2strike** [comment]
It turns out that using `mingw32-make.exe` rather than whatever make.exe I was using has resolved the issue. Issue resolved.
